export default [
  {
    redirect: [
      "read_me_first",
      "x2-read-me-first",
      "principle-1-a-role-is-a-promise",
      "x2-1-1-principle-1-a-role-is-a-promise",
      "principle-2-aria-can-both-cloak-and-enhance-creating-both-power-and-danger",
      "x2-1-2-principle-2-aria-can-both-cloak-and-enhance-creating-both-power-and-danger",
      "no_aria_better_bad_aria",
      "x2-1-no-aria-is-better-than-bad-aria",
      "browser_and_AT_support",
      "x2-2-browser-and-assistive-technology-support",
      "mobile_and_touch_support",
      "x2-3-mobile-and-touch-support",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/practices/read-me-first/",
    name: "Read Me First",
  },
  {
    redirect: ["aria_ex", "x3-design-patterns-and-widgets"],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/",
    name: "Patterns",
  },
  {
    redirect: [
      "accordion",
      "x3-1-accordion-sections-with-show-hide-functionality",
      "example",
      "keyboard-interaction",
      "wai-aria-roles-states-and-properties",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/accordion/",
    name: "Accordion Pattern",
  },
  {
    redirect: [
      "alert",
      "x3-2-alert",
      "example-0",
      "keyboard-interaction-0",
      "wai-aria-roles-states-and-properties-0",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/alert/",
    name: "Alert Pattern",
  },
  {
    redirect: [
      "alertdialog",
      "x3-3-alert-and-message-dialogs",
      "example-1",
      "keyboard-interaction-1",
      "wai-aria-roles-states-and-properties-1",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/alertdialog/",
    name: "Alert Dialog Pattern",
  },
  {
    redirect: [
      "breadcrumb",
      "x3-4-breadcrumb",
      "example-2",
      "keyboard-interaction-2",
      "wai-aria-roles-states-and-properties-2",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/breadcrumb/",
    name: "Breadcrumb Pattern",
  },
  {
    redirect: [
      "button",
      "x3-5-button",
      "issue-container-generatedID",
      "h-note",
      "examples",
      "keyboard-interaction-3",
      "wai-aria-roles-states-and-properties-3",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/button/",
    name: "Button Pattern",
  },
  {
    redirect: [
      "carousel",
      "x3-6-carousel-slide-show-or-image-rotator",
      "examples-0",
      "terms",
      "keyboard-interaction-4",
      "wai-aria-roles-states-and-properties-4",
      "basic-carousel-elements",
      "tabbed-carousel-elements",
      "grouped-carousel-elements",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/carousel/",
    name: "Carousel Pattern",
  },
  {
    redirect: [
      "checkbox",
      "x3-7-checkbox",
      "examples-1",
      "keyboard-interaction-5",
      "wai-aria-roles-states-and-properties-5",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/",
    name: "Checkbox Pattern",
  },
  {
    redirect: [
      "combobox",
      "x3-8-combobox",
      "examples-2",
      "keyboard-interaction-6",
      "combobox-keyboard-interaction",
      "issue-container-generatedID-0",
      "h-note-0",
      "listbox-popup-keyboard-interaction",
      "issue-container-generatedID-1",
      "h-note-1",
      "grid-popup-keyboard-interaction",
      "issue-container-generatedID-2",
      "h-note-2",
      "tree-popup-keyboard-interaction",
      "issue-container-generatedID-3",
      "h-note-3",
      "dialog-popup-keyboard-interaction",
      "issue-container-generatedID-4",
      "h-note-4",
      "wai-aria-roles-states-and-properties-6",
      "issue-container-generatedID-5",
      "h-note-5",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/combobox/",
    name: "Combobox Pattern",
  },
  {
    redirect: [
      "dialog_modal",
      "x3-9-dialog-modal",
      "examples-3",
      "keyboard-interaction-7",
      "issue-container-generatedID-6",
      "h-note-6",
      "dialog_roles_states_props",
      "wai-aria-roles-states-and-properties-7",
      "issue-container-generatedID-7",
      "h-note-7",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/",
    name: "Dialog Modal Pattern",
  },
  {
    redirect: [
      "disclosure",
      "x3-10-disclosure-show-hide",
      "examples-4",
      "keyboard-interaction-8",
      "wai-aria-roles-states-and-properties-8",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/",
    name: "Disclosure Pattern",
  },
  {
    redirect: [
      "feed",
      "x3-11-feed",
      "example-3",
      "keyboard-interaction-9",
      "issue-container-generatedID-8",
      "h-note-8",
      "wai-aria-roles-states-and-properties-9",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/feed/",
    name: "Feed Pattern",
  },
  {
    redirect: [
      "grid",
      "x3-12-grids-interactive-tabular-data-and-layout-containers",
      "examples-5",
      "dataGrid",
      "data-grids-for-presenting-tabular-information",
      "keyboard-interaction-for-data-grids",
      "issue-container-generatedID-9",
      "h-note-9",
      "issue-container-generatedID-10",
      "h-note-10",
      "layoutGrid",
      "layout-grids-for-grouping-widgets",
      "keyboard-interaction-for-layout-grids",
      "issue-container-generatedID-11",
      "h-note-11",
      "issue-container-generatedID-12",
      "h-note-12",
      "gridNav",
      "keyboard-interaction-setting-focus-and-navigating-inside-cells",
      "gridNav_focus",
      "whether-to-focus-on-a-cell-or-an-element-inside-it",
      "gridNav_inside",
      "editing-and-navigating-inside-a-cell",
      "grid_roles_states_props",
      "wai-aria-roles-states-and-properties-10",
      "issue-container-generatedID-13",
      "h-note-13",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/grid/",
    name: "Grid Pattern",
  },
  {
    redirect: [
      "link",
      "x3-13-link",
      "issue-container-generatedID-14",
      "h-note-14",
      "examples-6",
      "keyboard-interaction-10",
      "wai-aria-roles-states-and-properties-11",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/link/",
    name: "Link Pattern",
  },
  {
    redirect: [
      "Listbox",
      "x3-14-listbox",
      "examples-7",
      "listbox_kbd_interaction",
      "keyboard-interaction-11",
      "issue-container-generatedID-15",
      "h-note-15",
      "listbox_roles_states_props",
      "wai-aria-roles-states-and-properties-12",
      "issue-container-generatedID-16",
      "h-note-16",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/listbox/",
    name: "Listbox Pattern",
  },
  {
    redirect: [
      "menu",
      "x3-15-menu-or-menu-bar",
      "examples-8",
      "keyboard-interaction-12",
      "issue-container-generatedID-17",
      "h-note-17",
      "wai-aria-roles-states-and-properties-13",
      "issue-container-generatedID-18",
      "h-note-18",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/menubar/",
    name: "Menu Bar Pattern",
  },
  {
    redirect: [
      "menubutton",
      "x3-16-menu-button",
      "examples-9",
      "keyboard-interaction-13",
      "wai-aria-roles-states-and-properties-14",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/",
    name: "Menu Button Pattern",
  },
  {
    redirect: [
      "meter",
      "x3-17-meter",
      "issue-container-generatedID-19",
      "h-note-19",
      "example-4",
      "keyboard-interaction-14",
      "wai-aria-roles-states-and-properties-15",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/meter/",
    name: "Meter Pattern",
  },
  {
    redirect: [
      "radiobutton",
      "x3-18-radio-group",
      "examples-10",
      "keyboard-interaction-15",
      "for-radio-groups-not-contained-in-a-toolbar",
      "issue-container-generatedID-20",
      "h-note-20",
      "for-radio-group-contained-in-a-toolbar",
      "issue-container-generatedID-21",
      "h-note-21",
      "wai-aria-roles-states-and-properties-16",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/radio/",
    name: "Radio Pattern",
  },
  {
    redirect: [
      "slider",
      "x3-19-slider",
      "issue-container-generatedID-22",
      "h-warning",
      "examples-11",
      "slider_kbd_interaction",
      "keyboard-interaction-16",
      "issue-container-generatedID-23",
      "h-note-22",
      "slider_roles_states_props",
      "wai-aria-roles-states-and-properties-17",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/slider/",
    name: "Slider Pattern",
  },
  {
    redirect: [
      "slidertwothumb",
      "x3-20-slider-multi-thumb",
      "issue-container-generatedID-24",
      "h-warning-0",
      "example-5",
      "slidertwothumb_kbd_interaction",
      "keyboard-interaction-17",
      "wai-aria-roles-states-and-properties-18",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/slider-multithumb/",
    name: "Slider Multithumb Pattern",
  },
  {
    redirect: [
      "spinbutton",
      "x3-21-spinbutton",
      "example-6",
      "keyboard-interaction-18",
      "issue-container-generatedID-25",
      "h-note-23",
      "wai-aria-roles-states-and-properties-19",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/spinbutton/",
    name: "Spinbutton Pattern",
  },
  {
    redirect: [
      "switch",
      "x3-22-switch",
      "examples-12",
      "keyboard-interaction-19",
      "wai-aria-roles-states-and-properties-20",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/switch/",
    name: "Switch Pattern",
  },
  {
    redirect: [
      "table",
      "x3-23-table",
      "issue-container-generatedID-26",
      "h-note-24",
      "examples-13",
      "keyboard-interaction-20",
      "table_roles_states_props",
      "wai-aria-roles-states-and-properties-21",
      "issue-container-generatedID-27",
      "h-note-25",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/table/",
    name: "Table Pattern",
  },
  {
    redirect: [
      "tabpanel",
      "x3-24-tabs",
      "examples-14",
      "keyboard-interaction-21",
      "issue-container-generatedID-28",
      "h-note-26",
      "wai-aria-roles-states-and-properties-22",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/tabs/",
    name: "Tabs Pattern",
  },
  {
    redirect: [
      "toolbar",
      "x3-25-toolbar",
      "example-7",
      "keyboard-interaction-22",
      "issue-container-generatedID-29",
      "h-note-27",
      "wai-aria-roles-states-and-properties-23",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/toolbar/",
    name: "Toolbar Pattern",
  },
  {
    redirect: [
      "tooltip",
      "x3-26-tooltip-widget",
      "example-8",
      "keyboard-interaction-23",
      "issue-container-generatedID-30",
      "h-note-28",
      "wai-aria-roles-states-and-properties-24",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/",
    name: "Tooltip Pattern",
  },
  {
    redirect: [
      "TreeView",
      "x3-27-tree-view",
      "examples-15",
      "keyboard-interaction-24",
      "issue-container-generatedID-31",
      "h-note-29",
      "tree_roles_states_props",
      "wai-aria-roles-states-and-properties-25",
      "issue-container-generatedID-32",
      "h-note-30",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/treeview/",
    name: "Treeview Pattern",
  },
  {
    redirect: [
      "treegrid",
      "x3-28-treegrid",
      "examples-16",
      "keyboard-interaction-25",
      "issue-container-generatedID-33",
      "h-note-31",
      "issue-container-generatedID-34",
      "h-note-32",
      "treegrid_roles_states_props",
      "wai-aria-roles-states-and-properties-26",
      "issue-container-generatedID-35",
      "h-note-33",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/treegrid/",
    name: "Treegrid Pattern",
  },
  {
    redirect: [
      "windowsplitter",
      "x3-29-window-splitter",
      "example-9",
      "keyboard-interaction-26",
      "issue-container-generatedID-36",
      "h-note-34",
      "wai-aria-roles-states-and-properties-27",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/patterns/windowsplitter/",
    name: "Windowsplitter Pattern",
  },
  {
    redirect: [
      "aria_landmark",
      "x4-landmark-regions",
      "html-sectioning-elements",
      "x4-1-html-sectioning-elements",
      "general-principles-of-landmark-design",
      "x4-2-general-principles-of-landmark-design",
      "aria_lh_step3",
      "landmark-roles",
      "x4-3-landmark-roles",
      "aria_lh_banner",
      "x4-3-1-banner",
      "html-techniques",
      "aria-techniques",
      "examples-17",
      "aria_lh_complementary",
      "x4-3-2-complementary",
      "html-technique",
      "aria-technique",
      "examples-18",
      "aria_lh_contentinfo",
      "x4-3-3-contentinfo",
      "html-techniques-0",
      "aria-technique-0",
      "examples-19",
      "aria_lh_form",
      "x4-3-4-form",
      "html-techniques-1",
      "aria-technique-1",
      "examples-20",
      "aria_lh_main",
      "x4-3-5-main",
      "html-technique-0",
      "aria-technique-2",
      "examples-21",
      "aria_lh_navigation",
      "x4-3-6-navigation",
      "html-technique-1",
      "aria-technique-3",
      "examples-22",
      "aria_lh_region",
      "x4-3-7-region",
      "html-technique-2",
      "aria-technique-4",
      "examples-23",
      "aria_lh_search",
      "x4-3-8-search",
      "html-technique-3",
      "aria-technique-5",
      "examples-24",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/practices/landmark-regions/",
    name: "Landmarks Pattern",
  },
  {
    redirect: [
      "names_and_descriptions",
      "naming_role_guidance_heading",
      "x5-providing-accessible-names-and-descriptions",
      "names_and_descriptions_definition",
      "x5-1-what-are-accessible-names-and-descriptions",
      "names_and_descriptions_derivation",
      "x5-2-how-are-name-and-description-strings-derived",
      "naming_cardinal_rules",
      "x5-3-cardinal-rules-of-naming",
      "naming_rule_heed_warnings",
      "x5-3-1-rule-1-heed-warnings-and-test-thoroughly",
      "naming_rule_visible_text",
      "x5-3-2-rule-2-prefer-visible-text",
      "naming_rule_native_techniques",
      "x5-3-3-rule-3-prefer-native-techniques",
      "naming_rule_avoid_fallback",
      "x5-3-4-rule-4-avoid-browser-fallback",
      "naming_rule_brief_names",
      "x5-3-5-rule-5-compose-brief-useful-names",
      "naming_techniques",
      "x5-4-naming-techniques",
      "naming_with_child_content",
      "x5-4-1-naming-with-child-content",
      "issue-container-generatedID-37",
      "h-warning-1",
      "naming_with_aria-label",
      "x5-4-2-naming-with-a-string-attribute-via-aria-label",
      "issue-container-generatedID-38",
      "h-warning-2",
      "naming_with_aria-labelledby",
      "x5-4-3-naming-with-referenced-content-via-aria-labelledby",
      "issue-container-generatedID-39",
      "h-warning-3",
      "naming_with_labels",
      "x5-4-4-naming-form-controls-with-the-label-element",
      "naming_with_legends",
      "x5-4-5-naming-fieldsets-with-the-legend-element",
      "naming_with_captions",
      "x5-4-6-naming-tables-and-figures-with-captions",
      "naming_with_fallback",
      "x5-4-7-fallback-names-derived-from-titles-and-placeholders",
      "naming_effectively",
      "x5-5-composing-effective-and-user-friendly-accessible-names",
      "naming_role_guidance",
      "x5-6-accessible-name-guidance-by-role",
      "naming_role_guidance_heading",
      "name_calculation",
      "x5-7-accessible-name-calculation",
      "name_calculation_non-recursive_ex",
      "x5-7-1-examples-of-non-recursive-accessible-name-calculation",
      "name_calculation_recursive_ex",
      "x5-7-2-examples-of-recursive-accessible-name-calculation",
      "describing_techniques",
      "x5-8-describing-techniques",
      "describing_with_aria-describedby",
      "x5-8-1-describing-by-referencing-content-with-aria-describedby",
      "describing_with_captions",
      "x5-8-2-describing-tables-and-figures-with-captions",
      "describing_with_title",
      "x5-8-3-descriptions-derived-from-titles",
      "description_calculation",
      "x5-9-accessible-description-calculation",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/practices/names-and-descriptions/",
    name: "Providing Accessible Names and Descriptions",
  },
  {
    redirect: [
      "keyboard",
      "x6-developing-a-keyboard-interface",
      "kbd_generalnav",
      "x6-1-fundamental-keyboard-navigation-conventions",
      "kbd_focus_discernable_predictable",
      "x6-2-discernible-and-predictable-keyboard-focus",
      "kbd_focus_vs_selection",
      "x6-3-focus-vs-selection-and-the-perception-of-dual-focus",
      "kbd_selection_follows_focus",
      "x6-4-deciding-when-to-make-selection-automatically-follow-focus",
      "kbd_general_between",
      "x6-5-keyboard-navigation-between-components-the-tab-sequence",
      "kbd_general_within",
      "x6-6-keyboard-navigation-inside-components",
      "kbd_roving_tabindex",
      "x6-6-1-managing-focus-within-components-using-a-roving-tabindex",
      "kbd_focus_activedescendant",
      "x6-6-2-managing-focus-in-composites-using-aria-activedescendant",
      "kbd_disabled_controls",
      "x6-7-focusability-of-disabled-controls",
      "kbd_common_conventions",
      "x6-8-key-assignment-conventions-for-common-functions",
      "kbd_shortcuts",
      "x6-9-keyboard-shortcuts",
      "kbd_shortcuts_behavior_design",
      "x6-9-1-designing-the-scope-and-behavior-of-keyboard-shortcuts",
      "kbd_shortcuts_design_basic",
      "x6-9-1-1-ensure-basic-access-via-navigation",
      "kbd_shortcuts_design_choose_behavior",
      "x6-9-1-2-choose-appropriate-shortcut-behavior",
      "kbd_shortcuts_design_where",
      "x6-9-1-3-choose-where-to-add-shortcuts",
      "kbd_shortcuts_assigning",
      "x6-9-2-assigning-keyboard-shortcuts",
      "issue-container-generatedID-40",
      "h-note-35",
      "kbd_shortcuts_assignments_opsys_conflicts",
      "x6-9-2-1-operating-system-key-conflicts",
      "kbd_shortcuts_assignments_assistivetech_conflicts",
      "x6-9-2-2-assistive-technology-key-conflicts",
      "kbd_shortcuts_assignments_browser_conflicts",
      "x6-9-2-3-browser-key-conflicts",
      "kbd_shortcuts_assignments_intentional_conflicts",
      "x6-9-2-4-intentional-key-conflicts",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/practices/keyboard-interface/",
    name: "Developing a Keyboard Interface",
  },
  {
    redirect: [
      "gridAndTableProperties",
      "x7-grid-and-table-properties",
      "gridAndTableProperties_rows",
      "x7-1-using-aria-rowcount-and-aria-rowindex",
      "gridAndTableProperties_cols",
      "x7-2-using-aria-colcount-and-aria-colindex",
      "gridAndTableProperties_cols_contiguous",
      "x7-2-1-using-aria-colindex-when-column-indices-are-contiguous",
      "gridAndTableProperties_cols_noncontiguous",
      "x7-2-2-using-aria-colindex-when-column-indices-are-not-contiguous",
      "gridAndTableProperties_spans",
      "x7-3-defining-cell-spans-using-aria-colspan-and-aria-rowspan",
      "gridAndTableProperties_sort",
      "x7-4-indicating-sort-order-with-aria-sort",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/practices/grid-and-table-properties/",
    name: "Grid and Table Properties",
  },
  {
    redirect: [
      "range_related_properties",
      "x8-communicating-value-and-limits-for-range-widgets",
      "range_related_properties_using_aria-valuemin_aria-valuemax_and_aria-valuenow",
      "x8-1-using-aria-valuemin-aria-valuemax-and-aria-valuenow",
      "range_related_properties_using_aria-valuetext",
      "x8-2-using-aria-valuetext",
      "range_related_properties_meter_role",
      "x8-3-range-properties-with-meter",
      "range_related_properties_progressbar_role",
      "x8-4-range-properties-with-progress-bars",
      "range_related_properties_scrollbar_role",
      "x8-5-range-properties-with-scrollbars",
      "range_related_properties_slider_role",
      "x8-6-range-properties-with-sliders",
      "range_related_properties_spinbutton_role",
      "x8-7-range-properties-with-spin-buttons",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/practices/range-related-properties/",
    name: "Communicating Value and Limits for Range Widgets",
  },
  {
    redirect: [
      "presentation_role",
      "x9-intentionally-hiding-semantics-with-the-presentation-role",
      "presentation_role_effects",
      "x9-1-effects-of-role-presentation",
      "presentation_role_ignored",
      "x9-2-conditions-that-cause-role-presentation-to-be-ignored",
      "presentation_role_examples",
      "x9-3-example-demonstrating-effects-of-the-presentation-role",
      "children_presentational",
      "x10-roles-that-automatically-hide-semantics-by-making-their-descendants-presentational",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/practices/hiding-semantics/",
    name: "Hiding Semantics with the presentation Role",
  },
  {
    redirect: ["structural_roles", "x11-structural-roles"],
    to: "https://www.w3.org/WAI/ARIA/apg/practices/structural-roles/",
    name: "Structural Roles",
  },
  {
    redirect: ["indexes", "a-indexes"],
    to: "https://www.w3.org/WAI/ARIA/apg/example-index/",
    name: "Example Index",
  },
  {
    redirect: [
      "change_log",
      "b-change-history",
      "acknowledgements",
      "c-acknowledgements",
      "major-contributors-to-version-1-1",
      "c-1-major-contributors-to-version-1-1",
      "participants-active-in-the-aria-authoring-practices-task-force",
      "c-2-participants-active-in-the-aria-authoring-practices-task-force",
      "other-commenters-and-contributors-to-version-1-1",
      "c-3-other-commenters-and-contributors-to-version-1-1",
      "ack_funders",
      "c-4-enabling-funders",
      "references",
      "d-references",
      "informative-references",
      "d-1-informative-references",
    ],
    to: "https://www.w3.org/WAI/ARIA/apg/about/",
    name: "About",
  },
];
