name: JavaScript Linting
on:
  push:
    paths:
      - "package*.json"
      - ".eslint*"
      - "**/*.js"
      - ".github/workflows/lint-js.yml"
      - "!common/**"

  pull_request:
    paths:
      - "package*.json"
      - ".eslint*"
      - "**/*.js"
      - ".github/workflows/lint-js.yml"
      - "!common/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      # setup-node task is used without a particular version in order to load
      # the ESLint problem matchers
      - name: Set up Node.js
        uses: actions/setup-node@v1

      - name: Install npm dependencies
        run: npm ci

      - name: ESLint
        run: npm run lint:es
