name: Spellcheck

on:
  push:
    branches-ignore:
      - "dependabot/**"
    paths:
      - "**/*.*"
      - "!**/*.min.js"
      - "!**/*.pack.js"
      - "!**/*.paint"
      - "!content/patterns/landmarks/examples/css/bootstrap.css"
      - "!common/**"
      - "!respec-config.js"

  pull_request:
    paths:
      - "**/*.*"
      - "!**/*.min.js"
      - "!**/*.pack.js"
      - "!**/*.paint"
      - "!content/patterns/landmarks/examples/css/bootstrap.css"
      - "!common/**"
      - "!respec-config.js"

jobs:
  spelling:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: cSpell
        run: |
          echo "::add-matcher::.github/workflows/cspell-problem-matcher.json"
          npm run lint:spelling
