name: Spellcheck

on:
  push:
    paths:
      - "package*.json"
      - "cspell.json"
      - "aria-practices.html"
      - "examples/**/*.html"
      - ".github/workflows/cspell-problem-matcher.json"
      - ".github/workflows/spelling.yml"

  pull_request:
    paths:
      - "package*.json"
      - "cspell.json"
      - "aria-practices.html"
      - "examples/**/*.html"
      - ".github/workflows/cspell-problem-matcher.json"
      - ".github/workflows/spelling.yml"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.1.1

      - name: Install npm dependencies
        run: npm ci

      - name: cSpell
        run: |
          echo "::add-matcher::.github/workflows/cspell-problem-matcher.json"
          npm run lint:spelling
